Add cache-control and strict-transport-security headers
MetLifeLegalPlans/api-proxy pull request #1
Opened 2020-09-17 21:52 UTC by catchysong

2020-09-17 21:58 UTC, markrawls requested changes

2020-09-17 21:58 UTC, markrawls commented on Caddyfile
> +  header_up Strict-Transport-Security: max-age=31536000; includeSubDomains
`header_up` is for headers sent to the server, `header_down` is for requests sent to the browser. I think you've got them mixed up for everything except the Cache-Control directive

2020-09-17 21:58 UTC, markrawls commented on Caddyfile
> +  header_up Cache-Control no-cache, no-store
I'm not 100%, but I think values with spaces in them need to be quoted.

2020-09-23 21:13 UTC, ambikads approved these changes

2020-09-23 21:43 UTC, markrawls requested changes

2020-09-23 21:43 UTC, markrawls commented on Caddyfile
> +  header_down Cache-Control "no-cache, no-store"
This I disagree with - we want people to cache the large blobs from the frontend, everything there is publicly accessible and it helps with performance. Other than that, LGTM.

2020-09-23 22:30 UTC, catchysong commented on Caddyfile
> +  header_down Cache-Control "no-cache, no-store"
Cool I just changed it back to frame ancestors 'none'

2020-09-24 21:24 UTC, markrawls approved these changes

2020-09-24 21:36 UTC, merged